deployments:
  default:
    vm_size: 2G
    vm_storage_gb: 10G
    ready_wait: 120
    copy_files: /abcd ~/code
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: true
    squash_pr_comments: true
    auto_deploy_ttl: 30m
    auto_deploy_post_launch_commands:
      default:
        - echo true
        - python ./selenium_test.py
  branch:
    vm_size: 1
    vm_storage_gb: 13
    auto_deploy_disable_cache: true
    auto_deploy_on_commits: false
    auto_deploy_ttl: 5h
    ready_wait: 120
    filename: ./stuff/Dockerfile
    dockerfileonly: true
    context_path: ./stuff
    pipelines:
      - default:
          scripts:
            - ls -la

