deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    shell: sh
    deployment_page_commands:
      list something:
        - ls -la ./
        - sleep 2 && echo branch id is $SQUASH_BRANCH_WITH_ID
      target:
        stuff:
          - echo "branch id is $SQUASH_BRANCH_WITH_ID"
        alt:
          - bash -c 'echo commit is $SQUASH_COMMIT_SHA'
