deployments:
  default:
    vm_size: 1
    vm_storage_gb: 130
    deployment_type: docker
    ready_wait: 120
    filename: ./stuff/Dockerfile
    dockerfileonly: true
    port_forwarding:
      - 80
      - '3000'
    context_path: ./stuff
