deployments:
  default:
    vm_size: 1G
    vm_storage_gb: 10G
    success_response_check:
      fallback: true
      urls:
        - test--,/about/
        - test--,/
    allow_private_ports: 41234, 1010
    allow_public_ports: 8888, 48000
    subdomain_port_mapping:
      - test:3000
      - nginx:88
