version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
    environment:
      - TEST_VAL
      - TEST_VAL2
      - TEST
      - TEST1
      - TEST2
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
      - SQUASH_MASTER_DEPLOYMENT
      - ${SQUASH_BRANCH_WITH_ID}ABC
      - SOMETHING
      - SOMETHING2
      - a42
      - REGISTRY_PASSWORD
    command: bash ./run_server.sh
    volumes:
      - /assets:/assets
  
  alt-service:
      image: openresty/openresty:jessie
      ports:
        - 3000:80
