version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
    environment:
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
      - SQUASH_COMMIT_SHA
    command: bash ./run_server.sh
    volumes:
      - /assets:/assets
  
  alt-service:
      image: openresty/openresty:jessie
      ports:
        - 3000:80
    environment:
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
      - SQUASH_COMMIT_SHA
